# These are supported funding model platforms

github: # Radio.RF with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Radio.RF with a single Patreon username
open_collective: # Radio.RF with a single Open Collective username
ko_fi: # Radio.RF with a single Ko-fi username
tidelift: # Radio.RF with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Radio.RF with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Radio.RF with a single Liberapay username
issuehunt: # Radio.RF with a single IssueHunt username
otechie: # Radio.RF with a single Otechie username
lfx_crowdfunding: # Radio.RF with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Radio.RF with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
